/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BkdCc4HeZwn
 */
import Link from "next/link"

export function AboutMe() {
  return (
    <section className="flex flex-col items-center space-y-4 py-12 md:flex-row md:items-start md:space-x-6 md:space-y-0">
      <img
        alt="Developer Profile"
        className="rounded-full object-cover object-center"
        height="200"
        src="/placeholder.svg"
        style={{
          aspectRatio: "200/200",
          objectFit: "cover",
        }}
        width="200"
      />
      <div className="flex flex-col items-center space-y-2 md:items-start">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">John Doe</h2>
        <p className="max-w-md text-center text-zinc-500 dark:text-zinc-400 md:text-left md:text-lg/relaxed">
          I'm a web developer with over 5 years of experience, specializing in front-end development with React and
          modern CSS frameworks like Tailwind CSS. I also have experience in back-end development with Node.js and
          Express.
        </p>
        <Link
          className="inline-flex h-10 items-center justify-center rounded-md bg-zinc-900 px-8 text-sm font-medium text-zinc-50 shadow transition-colors hover:bg-zinc-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90 dark:focus-visible:ring-zinc-300"
          href="#"
        >
          Contact Me
        </Link>
      </div>
    </section>
  )
}
