/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zXMLhs9EYW1
 */


export function Education() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-6 text-center md:text-left">
          <div className="divide-y rounded-lg border border-zinc-200 dark:border-zinc-800">
            <div className="p-4 md:p-8">
              <h3 className="text-2xl font-bold">Harvard University</h3>
              <p className="text-lg text-zinc-500 dark:text-zinc-400">Bachelor of Science in Computer Science, 2018</p>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Focused on web development and user interface design.
              </p>
            </div>
            <div className="p-4 md:p-8">
              <h3 className="text-2xl font-bold">Stanford University</h3>
              <p className="text-lg text-zinc-500 dark:text-zinc-400">Master of Science in Computer Science, 2020</p>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Specialized in modern web frameworks and distributed systems.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
