
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/C2G38MPwk1F
 */


export function Skills() {
  return (
    <section className="py-12 md:py-24 lg:py-32">
    <div className="container mx-auto px-4 md:px-6 lg:px-10">
      <div className="space-y-4">
        <div className="grid grid-cols-5 items-center">
          <p className="col-span-1 text-lg font-semibold">JavaScript</p>
          <div className="col-span-4 ml-4 h-2 w-full rounded-full bg-zinc-200">
            <div
              className="h-full rounded-full rounded-l-xl bg-black"
              style={{
                width: "90%",
              }}
            />
          </div>
        </div>
        <div className="grid grid-cols-5 items-center">
          <p className="col-span-1 text-lg font-semibold">React</p>
          <div className="col-span-4 ml-4 h-2 w-full rounded-full bg-zinc-200">
            <div
              className="h-full rounded-full rounded-l-xl bg-black"
              style={{
                width: "85%",
              }}
            />
          </div>
        </div>
        <div className="grid grid-cols-5 items-center">
          <p className="col-span-1 text-lg font-semibold">Node.js</p>
          <div className="col-span-4 ml-4 h-2 w-full rounded-full bg-zinc-200">
            <div
              className="h-full rounded-full rounded-l-xl bg-black"
              style={{
                width: "80%",
              }}
            />
          </div>
        </div>
        <div className="grid grid-cols-5 items-center">
          <p className="col-span-1 text-lg font-semibold">Python</p>
          <div className="col-span-4 ml-4 h-2 w-full rounded-full bg-zinc-200">
            <div
              className="h-full rounded-full rounded-l-xl bg-black"
              style={{
                width: "70%",
              }}
            />
          </div>
        </div>
      </div>
    </div>
  </section>
  )
}
